### ISSUE TITLE
initializing vault with self signed certificate

### ISSUE THREAD

**Issue by ninjadude333** [rickardgranberg/terraform-provider-vaultoperator#11]
Hi,
when trying to init a vault with  a self signed certificate i get the error:

```
Error: Put "https://vault.xxx.com:8200/v1/sys/init": x509: certificate signed by unknown authority
│
│   with vaultoperator_init.example[0],
│   on main.tf line 191, in resource "vaultoperator_init" "example":
│  191: resource "vaultoperator_init" "example" {
```
is there any workaround for this issue ?

### Terraform Version
Terraform v1.3.5

thanks,
david.

**Comment by rickardgranberg** [comment]
If you're running it in K8s and have the http port available in the cluster, you can use the `kube_config` block to port forward into the cluster:
```
provider "vaultoperator" {
  kube_config {
    path       = "~/.kube/config"
    namespace  = "vault"
    service    = "vault"
    localPort  = "8200"
    remotePort = "8200"
  }
}
```

Otherwise, adding the root CA cert to your machine can be an option.

**Comment by ninjadude333** [comment]
great, 10x. will give it a try.
