### ISSUE TITLE
Feature Request: Vault Unseal

### ISSUE THREAD

**Issue by ChrisJBurns** [rickardgranberg/terraform-provider-vaultoperator#2]
Hi there,

Is there any chance we could get an `unseal` resource? Possibly taking the unseal keys from the `init` resource and feeding them into the `unseal` resource?

**Comment by rickardgranberg** [comment]
It's not on the list of things I planned to do, but I can see it being useful. This provider was created by myself to solve an immediate problem (doing Vault Init), so work on it is low priority for me at the moment.
I do accept pull requests though!

**Comment by venkatamutyala** [comment]
Is anyone working on this already?

**Comment by rickardgranberg** [comment]
> Is anyone working on this already?

Not to my knowledge, no.

**Comment by ChrisJBurns** [comment]
Hi, I believe this is currently being looked at by [Hashicorp](https://github.com/hashicorp/terraform-provider-vault/issues/122#issuecomment-1345392494). So there many not be any changes needed for in this repo
